rendering
infoBoxExampleData
  ^ {(Dictionary new
    at: #'icon' put: 'shoppingCart';
    at: #'label' put: 'Messages';
    at: #'number' put: 10380;
    at: #'widgetColor' put: 'aqua';
    at: #'progressValue' put: 30;
    at: #'progressDescription' put: 'Up 30% this week';
    at: #'footer' put: 'Up 30% this week';
    yourself).
  (Dictionary new
    at: #'icon' put: 'flagOutlined';
    at: #'label' put: 'Bookmarks';
    at: #'number' put: 410;
    at: #'widgetColor' put: 'green';
    at: #'progressValue' put: 65;
    at: #'progressDescription' put: 'Up 65 this week';
    at: #'footer' put: 'Up 30% this week';
    yourself).
  (Dictionary new
    at: #'icon' put: 'filesOutlined';
    at: #'label' put: 'Uploads';
    at: #'number' put: 13648;
    at: #'widgetColor' put: 'yellow';
    at: #'progressValue' put: 5;
    at: #'progressDescription' put: 'Up 5% this week';
    at: #'footer' put: 'Up 30% this week';
    yourself).
  (Dictionary new
    at: #'icon' put: 'star';
    at: #'label' put: 'Likes';
    at: #'number' put: 93139;
    at: #'widgetColor' put: 'red';
    at: #'progressValue' put: 90;
    at: #'progressDescription' put: 'Up 90% this week';
    at: #'footer' put: 'Up 30% this week';
    yourself)}